apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariogame
  labels:
    app: mariogame
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mariogame
  template:
    metadata:
      labels:
        app: mariogame
    spec:
      containers:
      - name: mariogame
        image: felipecosta09/mariogame:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mariogame
spec:
  type: LoadBalancer
  ports:
  - port: 8443
    targetPort: 8080
  selector:
    app: mariogame
